version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-filebrowser-quantum_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"

  server:
    image: gtstef/filebrowser:stable
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      TZ: Europe/Amsterdam
      FILEBROWSER_CONFIG: /home/filebrowser/config.yaml
      FILEBROWSER_DATABASE: /home/filebrowser/data/database.db
    volumes:
      - ./config.yaml:/home/filebrowser/config.yaml:ro
      - ${APP_DATA_DIR}/data:/home/filebrowser/data
      - ${APP_DATA_DIR}/files:/srv/app-files
      - ${UMBREL_ROOT}/home:/srv/umbrel-home
    command:
      - "--config"
      - "/home/filebrowser/config.yaml"
      - "--database"
      - "/home/filebrowser/data/database.db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
