services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-umbrelinit_init_1
      APP_PORT: 7891
 
  init:
    image: debian:bookworm-slim
    container_name: martinmeel-umbrelinit_init_1
    restart: on-failure
    privileged: true
    pid: host
    volumes:
      - /home/umbrel:/home/umbrel
    entrypoint: ["/bin/bash", "/home/umbrel/umbrel/app-data/martinmeel-umbrelinit/startup.sh"]
 
