services:
#app_proxy:
#    environment:
#      APP_HOST: martinmeel-gluetun_server_1
#      APP_PORT: 9696
#      # Use this if another app outside your umbrel device wants to connect via an API call
#      #PROXY_AUTH_WHITELIST: /api/*
#      # Set false if another app from outside your umbrell wants to connect without login!
#      PROXY_AUTH_ADD: 'false'
  gluetun-webui:
    image: scuzza/gluetun-webui:latest
    # container_name: gluetun-webui
    ports:
      - "127.0.0.1:3311:3000"
    environment:
      - GLUETUN_CONTROL_URL=http://gluetun:8000
      # Uncomment if Gluetun auth is enabled:
      #- GLUETUN_API_KEY=yourtoken
      #- GLUETUN_USER=username
      #- GLUETUN_PASSWORD=password
#   networks:
#      - umbrel_main_network
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3