services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-system-status_server_1
      APP_PORT: 3000

  server:
    image: node:20-alpine
    working_dir: /app
    command:
      - node
      - server.js
    ports:
      - "3011:3000"
    volumes:
      - ${APP_DATA_DIR}/server.js:/app/server.js:ro
      - ${APP_DATA_DIR}/static:/app/static:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${UMBREL_ROOT}/app-data:/host-app-data:ro
      - ${UMBREL_ROOT}/home:/host-home:ro
      - ${UMBREL_ROOT}/custom-hooks:/host-hooks:ro
      - /etc/systemd/system:/host-systemd:ro
      - /var/lib/dpkg/status:/host-dpkg-status:ro
    environment:
      - APP_PORT=3000
    restart: unless-stopped
