version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-compose-path-editor_server_1
      APP_PORT: 8099

  server:
    build: ./app
    restart: on-failure
    environment:
      HOST_UMBREL_ROOT: /host/umbrel
      APP_ID: martinmeel-compose-path-editor
    volumes:
      # Geeft de app toegang tot geïnstalleerde app compose-bestanden.
      # De backend valideert dat alleen docker-compose.yml bestanden binnen deze root
      # kunnen worden gelezen of gewijzigd.
      - ${UMBREL_ROOT}:/host/umbrel
