services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-termix_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/lukegus/termix:release-2.2.1.0@sha256:577c0e7024fa7767ffbd00e19a1e0ce28fb0027aab37c3f7d49e2c18bc001210
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    environment:
      PORT: "8080"
      DATA_DIR: "/app/data"
      GUACD_HOST: guacd
      GUACD_PORT: "4822"
    depends_on:
      - guacd

  guacd:
    image: guacamole/guacd:1.6.0
    restart: on-failure
    stop_grace_period: 1m
