services:
  app_proxy:
    environment:
      APP_HOST: termix_web
      APP_PORT: 8034
 
  termix_web:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix_web
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    environment:
      PORT: "8084"
    depends_on:
      - termix_guacd
 
  termix_guacd:
    image: guacamole/guacd:1.6.0
    container_name: termix_guacd
    restart: on-failure
    stop_grace_period: 1m