services:
  server:
    image: qmcgaw/gluetun:3.41.1@sha256:bd84f4f090ca61170c8329a72d4f451255b01f6489486a621bfcb89749fb80ab
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # HTTP proxy (needed when using gluetun as a proxy for other apps)
      - 8888:8888
      - 8000:8000
      # If you need Shadowsocks, you can add the ports here. 
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      # It seems that it is not needed to add the portnumbers of the applications that you need to work via gluetun.
      # Experiment if you find some strange behaviour!!
      # Sonarr
      # - 8989:8989
      # Radarr
      # - 7878:7878
      # Seerr
      # - 5055:5055
      # Tautulli
      # - 8181:8181
      # Profilarr
      # - 6868:6868
      # Prowlarr
      # - 9696:9696
      # SABnzbd
      # - 8080:8080
      # qBittorrent
      # - 8090:8090
      # Spotweb
      # - 81:80
    volumes:
      - ${APP_DATA_DIR}/data:/gluetun
    environment:
      # PLEASE READ ALSO the Gluetun WIKI page: https://github.com/qdm12/gluetun-wiki for more info on how to use it. 
      # ProtonVPN VPN Configuration
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTONVPN_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      # MTU, change if needed
      - WIREGUARD_MTU=1360
      # Enble Control server
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_LOG=on
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}
      # Enable HTTP proxy
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      # Enable port forwarding. Note! Make sure you use a private key (protonVPN) which covers the portforwarding option.
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      # Script that automatically updates portforwarding on qBittorrent.
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}},\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8090/api/v2/app/setPreferences 2>&1'
      - VPN_PORT_FORWARDING_DOWN_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":0}" http://127.0.0.1:8090/api/v2/app/setPreferences 2>&1'
      # Enable the firewall
      # - FIREWALL=on
      # Allow local network access
      - FIREWALL_OUTBOUND_SUBNETS=192.168.2.0/24 # Use your own network. 
      # Timezone
      - TZ=Europe/Amsterdam
      # Health checks
      - HEALTH_ENABLED=on
      - HEALTH_TARGET_ADDRESSES=cloudflare.com:443,github.com:443
      - HEALTH_ICMP_TARGET_IPS=1.1.1.1,8.8.8.8
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - HEALTH_RESTART_VPN=on
      # DNS configuration
      - DNS_UPSTREAM_RESOLVERS=cloudflare
      - DNS_UPSTREAM_RESOLVER_TYPE=dot
      - DNS_UPSTREAM_IPV6=off
      - DNS_CACHING=off
      # Gluetun version information
      - VERSION_INFORMATION=off
      # Help Gluetun from AI scrapping
      - BORINGPOLL_GLUETUNCOM=off
      # Especially for ProtonVPN?
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
    restart: on-failure
    stop_grace_period: 1m
